# SAM configuration file for Impact Compendium Backend
version = 0.1

[default]
[default.global.parameters]
stack_name = "impact-compendium-backend-prod"
profile = "IBD-DEV"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
stack_name = "impact-compendium-backend-prod"
s3_prefix = "impact-compendium-backend"
region = "us-east-1"
profile = "IBD-DEV"
parameter_overrides = "Stage=prod"
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true
